verifying jks

diff --git a/.github/workflows/app-release.yml b/.github/workflows/app-release.yml
--- a/.github/workflows/app-release.yml
+++ b/.github/workflows/app-release.yml
@@ -136,7 +136,7 @@ jobs:
 
           for APP in $APPS; do
             # use --arg so keys with dashes or special chars work
-            STORE_FILE=android/keystore/${APP}.jks
+            STORE_FILE=../keystore/${APP}.jks
             STORE_PASS=$(jq -r --arg app "$APP" '.apps[$app].android.keystore.store_password' config.json)
             KEY_ALIAS=$(jq -r --arg app "$APP" '.apps[$app].android.keystore.key_alias' config.json)
             KEY_PASS=$(jq -r --arg app "$APP" '.apps[$app].android.keystore.key_password' config.json)
@@ -309,8 +309,8 @@ jobs:
         run: |
           echo "${{ needs.extract-flavors.outputs.config_b64 }}" | base64 --decode > config.json
 
-      # Restore signing.properties
-      - name:  ${{ matrix.flavor }} Keystore
+      # Restore Keystore
+      - name: Restore Keystore ${{ matrix.flavor }}
         run: |
           mkdir -p android/keystore
           
@@ -335,6 +335,34 @@ jobs:
           echo "----- signing.properties content -----"
           cat android/signing.properties
           echo "--------------------------------------"
+
+      - name: Verify JKS ${{ matrix.flavor }}
+        run: |
+          FLAVOR="${{ matrix.flavor }}"
+
+          # Read required fields from signing.properties
+          STORE_FILE=$(grep "${FLAVOR}.storeFile" android/signing.properties | cut -d'=' -f2)
+          STORE_PASS=$(grep "${FLAVOR}.storePassword" android/signing.properties | cut -d'=' -f2)
+          KEY_ALIAS=$(grep "${FLAVOR}.keyAlias" android/signing.properties | cut -d'=' -f2)
+          KEY_PASS=$(grep "${FLAVOR}.keyPassword" android/signing.properties | cut -d'=' -f2)
+
+          echo "STORE_FILE=$STORE_FILE"
+          echo "KEY_ALIAS=$KEY_ALIAS"
+
+          echo "🔎 Checking JKS integrity..."
+
+          keytool -list -v \
+            -keystore "$STORE_FILE" \
+            -storepass "$STORE_PASS" \
+            -alias "$KEY_ALIAS" \
+            >/dev/null 2>&1
+
+          if [ $? -ne 0 ]; then
+            echo "❌ ERROR: Keystore '$STORE_FILE' is INVALID or CORRUPTED"
+            exit 1
+          fi
+
+          echo "✅ Keystore is valid: $STORE_FILE"
 
       - name: Restore Play JSON
         run: |
